### PR TITLE
Don't tag repository on publishing (CI doesn't push back anyway)

### PR DESCRIPTION
**Pull request by fearthecowboy**

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.21*

## ❌️ General: 94%

<details><summary>30 out of 528 features are not covered by tests</summary><p>

[`ConstantsInBody`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInBody), [`ConstantsInPath`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInPath), [`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`OptionalArrayParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalArrayParameter), [`OptionalClassParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalClassParameter), [`OptionalImplicitBody`](https://github.com/Azure/autorest.testserver/search?q=OptionalImplicitBody), [`OptionalIntegerParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalIntegerParameter), [`OptionalStringParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalStringParameter), [`UrlPathsArrayCSVInPath`](https://github.com/Azure/autorest.testserver/search?q=UrlPathsArrayCSVInPath), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`putStringNull`](https://github.com/Azure/autorest.testserver/search?q=putStringNull), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 88%

<details><summary>13 out of 118 features are not covered by tests</summary><p>

[`AzureMethodQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureMethodQueryUrlEncoding), [`AzureODataFilter`](https://github.com/Azure/autorest.testserver/search?q=AzureODataFilter), [`AzurePathQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzurePathQueryUrlEncoding), [`AzureRequestClientIdInError`](https://github.com/Azure/autorest.testserver/search?q=AzureRequestClientIdInError), [`AzureSwaggerQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureSwaggerQueryUrlEncoding), [`AzureXmsCustomNamedRequestIdParameterGroup`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsCustomNamedRequestIdParameterGroup), [`AzureXmsRequestClientIdNull`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsRequestClientIdNull), [`CustomHeaderPostAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostAsyncSucceded), [`CustomHeaderPostSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostSucceeded), [`CustomHeaderPutAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutAsyncSucceded), [`CustomHeaderPutSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutSucceeded), [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson), [`PagingOdataMultiple`](https://github.com/Azure/autorest.testserver/search?q=PagingOdataMultiple)</p></details>

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.21*

## ❌️ General: 94%

<details><summary>30 out of 528 features are not covered by tests</summary><p>

[`ConstantsInBody`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInBody), [`ConstantsInPath`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInPath), [`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`OptionalArrayParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalArrayParameter), [`OptionalClassParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalClassParameter), [`OptionalImplicitBody`](https://github.com/Azure/autorest.testserver/search?q=OptionalImplicitBody), [`OptionalIntegerParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalIntegerParameter), [`OptionalStringParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalStringParameter), [`UrlPathsArrayCSVInPath`](https://github.com/Azure/autorest.testserver/search?q=UrlPathsArrayCSVInPath), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`putStringNull`](https://github.com/Azure/autorest.testserver/search?q=putStringNull), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 88%

<details><summary>13 out of 118 features are not covered by tests</summary><p>

[`AzureMethodQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureMethodQueryUrlEncoding), [`AzureODataFilter`](https://github.com/Azure/autorest.testserver/search?q=AzureODataFilter), [`AzurePathQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzurePathQueryUrlEncoding), [`AzureRequestClientIdInError`](https://github.com/Azure/autorest.testserver/search?q=AzureRequestClientIdInError), [`AzureSwaggerQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureSwaggerQueryUrlEncoding), [`AzureXmsCustomNamedRequestIdParameterGroup`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsCustomNamedRequestIdParameterGroup), [`AzureXmsRequestClientIdNull`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsRequestClientIdNull), [`CustomHeaderPostAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostAsyncSucceded), [`CustomHeaderPostSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostSucceeded), [`CustomHeaderPutAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutAsyncSucceded), [`CustomHeaderPutSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutSucceeded), [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson), [`PagingOdataMultiple`](https://github.com/Azure/autorest.testserver/search?q=PagingOdataMultiple)</p></details>

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by olydis** [comment]
# 🤖 AutoRest automatic publish job 🤖
~~~ Haskell
> will publish once PR gets merged
~~~

**Comment by daschult** [comment]
> linux-x64 restart

**Comment by daschult** [comment]
> win32-x64 restart

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.27*

## ❌️ General: 90%

<details><summary>53 out of 544 features are not covered by tests</summary><p>

[`ConstantsInBody`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInBody), [`ConstantsInPath`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInPath), [`HttpRedirect300Get`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect300Get), [`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`OptionalArrayParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalArrayParameter), [`OptionalClassParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalClassParameter), [`OptionalImplicitBody`](https://github.com/Azure/autorest.testserver/search?q=OptionalImplicitBody), [`OptionalIntegerParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalIntegerParameter), [`OptionalStringParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalStringParameter), [`UrlPathsArrayCSVInPath`](https://github.com/Azure/autorest.testserver/search?q=UrlPathsArrayCSVInPath), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getDateInvalid`](https://github.com/Azure/autorest.testserver/search?q=getDateInvalid), [`getDecimalBig`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBig), [`getDecimalBigNegativeDecimal`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBigNegativeDecimal), [`getDecimalBigPositiveDecimal`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBigPositiveDecimal), [`getDecimalInvalid`](https://github.com/Azure/autorest.testserver/search?q=getDecimalInvalid), [`getDecimalSmall`](https://github.com/Azure/autorest.testserver/search?q=getDecimalSmall), [`getDictionaryNullkey`](https://github.com/Azure/autorest.testserver/search?q=getDictionaryNullkey), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`getIntegerOverflow`](https://github.com/Azure/autorest.testserver/search?q=getIntegerOverflow), [`getIntegerUnderflow`](https://github.com/Azure/autorest.testserver/search?q=getIntegerUnderflow), [`getLongOverflow`](https://github.com/Azure/autorest.testserver/search?q=getLongOverflow), [`getLongUnderflow`](https://github.com/Azure/autorest.testserver/search?q=getLongUnderflow), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putDecimalBig`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBig), [`putDecimalBigNegativeDecimal`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBigNegativeDecimal), [`putDecimalBigPositiveDecimal`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBigPositiveDecimal), [`putDecimalSmall`](https://github.com/Azure/autorest.testserver/search?q=putDecimalSmall), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`putStringNull`](https://github.com/Azure/autorest.testserver/search?q=putStringNull), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 88%

<details><summary>13 out of 118 features are not covered by tests</summary><p>

[`AzureMethodQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureMethodQueryUrlEncoding), [`AzureODataFilter`](https://github.com/Azure/autorest.testserver/search?q=AzureODataFilter), [`AzurePathQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzurePathQueryUrlEncoding), [`AzureRequestClientIdInError`](https://github.com/Azure/autorest.testserver/search?q=AzureRequestClientIdInError), [`AzureSwaggerQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureSwaggerQueryUrlEncoding), [`AzureXmsCustomNamedRequestIdParameterGroup`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsCustomNamedRequestIdParameterGroup), [`AzureXmsRequestClientIdNull`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsRequestClientIdNull), [`CustomHeaderPostAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostAsyncSucceded), [`CustomHeaderPostSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostSucceeded), [`CustomHeaderPutAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutAsyncSucceded), [`CustomHeaderPutSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutSucceeded), [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson), [`PagingOdataMultiple`](https://github.com/Azure/autorest.testserver/search?q=PagingOdataMultiple)</p></details>

**Comment by daschult** [comment]
@fearthecowboy Hey Garrett. What's the status of this pull request? Is there any work being done to get it working or is there anything needed from us?

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 2.3.27*

## ❌️ General: 90%

<details><summary>53 out of 544 features are not covered by tests</summary><p>

[`ConstantsInBody`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInBody), [`ConstantsInPath`](https://github.com/Azure/autorest.testserver/search?q=ConstantsInPath), [`HttpRedirect300Get`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect300Get), [`HttpRedirect301Put`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect301Put), [`HttpRedirect302Patch`](https://github.com/Azure/autorest.testserver/search?q=HttpRedirect302Patch), [`OptionalArrayParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalArrayParameter), [`OptionalClassParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalClassParameter), [`OptionalImplicitBody`](https://github.com/Azure/autorest.testserver/search?q=OptionalImplicitBody), [`OptionalIntegerParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalIntegerParameter), [`OptionalStringParameter`](https://github.com/Azure/autorest.testserver/search?q=OptionalStringParameter), [`UrlPathsArrayCSVInPath`](https://github.com/Azure/autorest.testserver/search?q=UrlPathsArrayCSVInPath), [`UrlQueriesArrayMultiEmpty`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiEmpty), [`UrlQueriesArrayMultiNull`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiNull), [`UrlQueriesArrayMultiValid`](https://github.com/Azure/autorest.testserver/search?q=UrlQueriesArrayMultiValid), [`additionalPropertiesInProperties`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInProperties), [`additionalPropertiesInPropertiesWithAPTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesInPropertiesWithAPTypeString), [`additionalPropertiesTrue`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTrue), [`additionalPropertiesTypeObject`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeObject), [`additionalPropertiesTypeString`](https://github.com/Azure/autorest.testserver/search?q=additionalPropertiesTypeString), [`allowedValueEnum`](https://github.com/Azure/autorest.testserver/search?q=allowedValueEnum), [`animalNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=animalNotFoundError), [`expectedEnum`](https://github.com/Azure/autorest.testserver/search?q=expectedEnum), [`expectedNoErrors`](https://github.com/Azure/autorest.testserver/search?q=expectedNoErrors), [`expectedPetHungryError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetHungryError), [`expectedPetSadError`](https://github.com/Azure/autorest.testserver/search?q=expectedPetSadError), [`getComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=getComplexPolymorphismComplicated), [`getDateInvalid`](https://github.com/Azure/autorest.testserver/search?q=getDateInvalid), [`getDecimalBig`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBig), [`getDecimalBigNegativeDecimal`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBigNegativeDecimal), [`getDecimalBigPositiveDecimal`](https://github.com/Azure/autorest.testserver/search?q=getDecimalBigPositiveDecimal), [`getDecimalInvalid`](https://github.com/Azure/autorest.testserver/search?q=getDecimalInvalid), [`getDecimalSmall`](https://github.com/Azure/autorest.testserver/search?q=getDecimalSmall), [`getDictionaryNullkey`](https://github.com/Azure/autorest.testserver/search?q=getDictionaryNullkey), [`getEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferenced), [`getEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=getEnumReferencedConstant), [`getIntegerOverflow`](https://github.com/Azure/autorest.testserver/search?q=getIntegerOverflow), [`getIntegerUnderflow`](https://github.com/Azure/autorest.testserver/search?q=getIntegerUnderflow), [`getLongOverflow`](https://github.com/Azure/autorest.testserver/search?q=getLongOverflow), [`getLongUnderflow`](https://github.com/Azure/autorest.testserver/search?q=getLongUnderflow), [`intError`](https://github.com/Azure/autorest.testserver/search?q=intError), [`linkNotFoundError`](https://github.com/Azure/autorest.testserver/search?q=linkNotFoundError), [`putComplexPolymorphismComplicated`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismComplicated), [`putComplexPolymorphismNoDiscriminator`](https://github.com/Azure/autorest.testserver/search?q=putComplexPolymorphismNoDiscriminator), [`putDecimalBig`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBig), [`putDecimalBigNegativeDecimal`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBigNegativeDecimal), [`putDecimalBigPositiveDecimal`](https://github.com/Azure/autorest.testserver/search?q=putDecimalBigPositiveDecimal), [`putDecimalSmall`](https://github.com/Azure/autorest.testserver/search?q=putDecimalSmall), [`putEnumReferenced`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferenced), [`putEnumReferencedConstant`](https://github.com/Azure/autorest.testserver/search?q=putEnumReferencedConstant), [`putStringNull`](https://github.com/Azure/autorest.testserver/search?q=putStringNull), [`roundTripEnum`](https://github.com/Azure/autorest.testserver/search?q=roundTripEnum), [`stringError`](https://github.com/Azure/autorest.testserver/search?q=stringError), [`unexpectedEnum`](https://github.com/Azure/autorest.testserver/search?q=unexpectedEnum)</p></details>

## ❌️ Azure: 88%

<details><summary>13 out of 118 features are not covered by tests</summary><p>

[`AzureMethodQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureMethodQueryUrlEncoding), [`AzureODataFilter`](https://github.com/Azure/autorest.testserver/search?q=AzureODataFilter), [`AzurePathQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzurePathQueryUrlEncoding), [`AzureRequestClientIdInError`](https://github.com/Azure/autorest.testserver/search?q=AzureRequestClientIdInError), [`AzureSwaggerQueryUrlEncoding`](https://github.com/Azure/autorest.testserver/search?q=AzureSwaggerQueryUrlEncoding), [`AzureXmsCustomNamedRequestIdParameterGroup`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsCustomNamedRequestIdParameterGroup), [`AzureXmsRequestClientIdNull`](https://github.com/Azure/autorest.testserver/search?q=AzureXmsRequestClientIdNull), [`CustomHeaderPostAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostAsyncSucceded), [`CustomHeaderPostSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPostSucceeded), [`CustomHeaderPutAsyncSucceded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutAsyncSucceded), [`CustomHeaderPutSucceeded`](https://github.com/Azure/autorest.testserver/search?q=CustomHeaderPutSucceeded), [`LRONonRetryPut201Creating400InvalidJson`](https://github.com/Azure/autorest.testserver/search?q=LRONonRetryPut201Creating400InvalidJson), [`PagingOdataMultiple`](https://github.com/Azure/autorest.testserver/search?q=PagingOdataMultiple)</p></details>

**Comment by fearthecowboy** [comment]
It corrects a minor glitch in publishing, you can merge it anytime.

**Pull request merged**
