### PR TITLE
fix: add subtype at import list

### PR DESCRIPTION
**Pull request by ChenTanyi**
fix https://github.com/test-repo-billy/azure-rest-api-specs/pull/378

### CODE REVIEW

**Comment by ChenTanyi** [comment]
@yaohaizh @weidongxu-microsoft

**Comment by ChenTanyi** [comment]
https://github.com/Azure/azure-libraries-for-java/issues/882

**Comment by ChenTanyi** [comment]
@jianghaolu could you review this PR? Thanks.

**Comment by jianghaolu** [comment]
Can you help me understand why the sub types need to imported? They should all be the in the same models package?

**Comment by ChenTanyi** [comment]
@jianghaolu in the sdk automation I point to https://github.com/test-repo-billy/azure-rest-api-specs/pull/378, there is compilation error due to subtype import error. The json property use subtype, but the subtype has not been imported. This is why I add the subtype import to fix the error.

**Pull request closed without merging**
