### PR TITLE
Replace logging with plugin logger

### PR DESCRIPTION
**Pull request by jianghaolu**
image

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
LGTM

**Comment by weidongxu-microsoft** [comment]
@jianghaolu 

For the error in CI, you can disable the surefire https://github.com/Azure/autorest.java/blob/v4/fluentgen/pom.xml#L102-L111

I will check it later.

**Comment by weidongxu-microsoft** [comment]
I've put a PR to disable the tests https://github.com/Azure/autorest.java/pull/799

**Comment by jianghaolu** [comment]
Thanks!

**Pull request merged**
