### PR TITLE
mgmt, resource collection association

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
fix https://github.com/Azure/autorest.java/issues/2149

eventgrid config:

```
resource-collection-association:
- resource: EventSubscription
  collection: TopicEventSubscriptions
```

### CODE REVIEW

**Review by XiaofeiCao — APPROVED** [review]

**Comment by XiaofeiCao** [comment]
Should we map `EventSubscription` to `EventSubscription`? 
Current generated code seems wrong to me. It is calling `serviceClient().getTopicEventSubscriptions()` in its `create()` function. Instead, I believe it should call `serviceClient.getEventSubscriptions()`(it should have no `topics` information in `EventSubscriptions`)?

`create()` in `EventSubscriptionImpl`: https://github.com/Azure/azure-sdk-for-java/blob/main/sdk/eventgrid/azure-resourcemanager-eventgrid/src/main/java/com/azure/resourcemanager/eventgrid/implementation/EventSubscriptionImpl.java#L137-L138

swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/stable/2022-06-15/EventGrid.json#L1204

**Comment by weidongxu-microsoft** [comment]
From guide here seems right?

https://learn.microsoft.com/en-us/azure/event-grid/scripts/cli-subscribe-custom-topic#run-the-script

It would create a topic first, then create the event subscription.

Though not sure if there is other way to create event subscription (non custom topic?).

**Comment by weidongxu-microsoft** [comment]
I remember that at first, `EventSubscription` follow this path https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L2736, "resource from scope"
Seems OK.

Then this was added https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L2067 and it moved to "subresource from resource group"
This seems the correct one. Better than the one above.

**Comment by XiaofeiCao** [comment]
There is one without `topics`, only `domain`:
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L3628

Though response is also `EventSubscription` and it always has `topics` property. 
https://github.com/Azure/azure-rest-api-specs/blob/main/specification/eventgrid/resource-manager/Microsoft.EventGrid/preview/2023-06-01-preview/EventGrid.json#L13413-L13421

**Comment by weidongxu-microsoft** [comment]
OK, maybe we can move it back to "scope as parent", it is be more generic? We should be able to add another field e.g. "type: SCOPE_AS_PARENT" to have it match the scope first.

**Comment by XiaofeiCao** [comment]
Agree, `withScope` definitely seems more appropriate.

**Pull request merged**
