### PR TITLE
Add ExpandableStringEnum to EnumTemplate.cshtml, fix LROSADsTests

### PR DESCRIPTION
**Pull request by daschult**

### CODE REVIEW

**Comment by daschult** [comment]
Closed and re-opened to trigger CI to re-run.

**Comment by daschult** [comment]
@jianghaolu Can you take a quick look and make sure I didn't do anything really dumb?

**Comment by olydis** [comment]
reopened for demo purposes during AutoRest bi-weekly meeting

**Comment by daschult** [comment]
@olydis What permissions do I need to be able to merge this pull request?

**Comment by olydis** [comment]
oh, I guess you weren't added to the necessary GitHub group, I'll add you 🙂

**Pull request merged**
