### PR TITLE
Update dependencies and regenerate

### PR DESCRIPTION
**Pull request by daschult**

### CODE REVIEW

**Comment by RikkiGibson** [comment]
> linux-x64 restart

**Comment by RikkiGibson** [comment]
> win32-x64 restart

**Comment by daschult** [comment]
win32-x64 restart

**Comment by daschult** [comment]
> win32-x64 restart

**Comment by daschult** [comment]
@olydis Isn't that how I'm supposed to restart win32-x64 checks?

**Comment by olydis** [comment]
just write "> win32-x64 restart", the code formatting is the signal that it got picked up (will change that to some emoji reaction when I get the chance)

**Pull request merged**
