### PR TITLE
Update runtime package

### PR DESCRIPTION
**Pull request by RikkiGibson**
CI should actually pass on this one because we're actually publishing the runtime snapshots now :+1:

### CODE REVIEW

**Comment by RikkiGibson** [comment]
@olydis Is something going on with CI?

**Comment by RikkiGibson** [comment]
```
Tests run: 13, Failures: 1, Errors: 1, Skipped: 0, Time elapsed: 0.047 sec <<< FAILURE! - in fixtures.bodystring.StringOperationsTests
putMbcs(fixtures.bodystring.StringOperationsTests)  Time elapsed: 0 sec  <<< ERROR!
```
This test passes locally when running 
```
mvn test -pl test/vanilla/ -Dtest=StringOperationsTests#putMbcs
```

**Comment by olydis** [comment]
> win32-x64 restart

**Comment by RikkiGibson** [comment]
This test passes on the command line and IDE on the Mac and in the IDE in Windows, but fails on the command line in Windows.

**Comment by RikkiGibson** [comment]
It's a runtime bug-- will PR/publish/rerun

**Comment by RikkiGibson** [comment]
> win32-x64 restart

**Comment by RikkiGibson** [comment]
~~~
> win32-x64 restart
~~~

**Comment by RikkiGibson** [comment]
@jianghaolu Seems like CoverageReporter stalls the tests out--should this be changed?

**Comment by RikkiGibson** [comment]
:tada:

**Pull request merged**
