### PR TITLE
tsp, generate origin (JSON) example file name in mgmt sample files

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
fix https://github.com/Azure/autorest.java/issues/2788

code for `x-ms-original-file` https://github.com/Azure/autorest.java/pull/2789/commits/f6dd96b7a35cac35cdca69e5a68ce3956542840d
code for convert that to the relative path in sample file https://github.com/Azure/autorest.java/pull/2789/commits/979314768a9718465d26b9ad3896a3e4bc942a3e

UT with some refactor https://github.com/Azure/autorest.java/pull/2789/commits/5db62b916bf13ebbfe16a09c6b9bb914ac8da02e

test
```diff
  * Samples for StandbyVirtualMachinePools Update.
  */
 public final class StandbyVirtualMachinePoolsUpdateSamples {
+    /*
+     * x-ms-original-file:
+     * specification/standbypool/StandbyPool.Management/examples/2023-12-01-preview/
+     * StandbyVirtualMachinePools_Update.json
+     */
     /**
      * Sample code: StandbyVirtualMachinePools_Update.
      *
```

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
The reason of the error in https://dev.azure.com/azure-sdk/internal/_build/results?buildId=3823237&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=0750e130-1e9a-5b8a-35b2-9986f25ac898 is that now even `ClassType` class needs JavaSettings, which must be mocked before test.

Hence added BeforeAllTestsExtension for javagen and fluentgen module test https://github.com/Azure/autorest.java/pull/2789/commits/5bcb150cffd9c7a1c4045cfae7315a403d4c673f

**Review by XiaofeiCao — APPROVED** [review]

**Comment by XiaofeiCao** [comment]
Wonder why there's no change in generated samples..

**Comment by weidongxu-microsoft** [comment]
> Wonder why there's no change in generated samples. (no collection for DPG)

I think we only do this for fluent. Your `arm.tsp` probably not having example file?

**Comment by XiaofeiCao** [comment]
> I think we only do this for fluent. Your `arm.tsp` probably not having example file?

Yeah, let me add them later.

**Pull request merged**
