### PR TITLE
Use RxJava2

### PR DESCRIPTION
**Pull request by RikkiGibson**
This PR starts the work to generate code compatible with RxJava2. The generated code doesn't compile currently. Once the fixes are made, in order to compile it, you'll need to `mvn install` the RxJava2 branch of autorest-clientruntime-for-java, or merge RxJava2 and publish a snapshot.

Remaining items include:
- Using Completable return types in the ServiceClient interface, and updating anywhere else that `Single<Void>` is still in use
- Adding `@Ignore` to test cases like Arrays.getNull, or changing the test methods to use the RestResponse variants.

### CODE REVIEW

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by RikkiGibson** [comment]
Just a few build errors outstanding related to HttpPipeline. Optimistic there won't be much work left to get the Azure and Fluent tests passing.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by RikkiGibson** [comment]
Tests are all passing locally. Will need to publish a snapshot using autorest-clientruntime-for-java RxJava2 branch before they will pass in CI.

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by olydis** [comment]
# 🤖 AutoRest automatic feature coverage report 🤖
*feature set version 1.9.2*

## ❌️ General: 0%

no tests were run for this category


## ❌️ Azure: 0%

no tests were run for this category

**Comment by RikkiGibson** [comment]
I should have asked for review on this before merging--would still like to get feedback and address anything that stands out to you @daschult

**Pull request merged**
