### PR TITLE
fix credential check error, add 'secret' as key word

### PR DESCRIPTION
**Pull request by haolingdong-msft**
Fix  this build error: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1912619&view=logs&j=2e58d666-b5db-5758-0ec7-32f7d1b2592f&t=846c2b5b-32b8-5a48-6bf5-0ea739aa23f0&l=104

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
You should wait for CI pass before merge?

**Comment by haolingdong-msft** [comment]
Ah yes, sorry that I thought I was enabling auto merge previously, but it get merged immediately. Does autorest.java has automerge function?

**Comment by weidongxu-microsoft** [comment]
automerge is not enabled, and I am not sure how it works without a required CI.

so, for now, just use your common sense.

**Comment by haolingdong-msft** [comment]
CIs on main  branch passed.

**Pull request merged**
