### PR TITLE
Fabric Bot Configuration

### PR DESCRIPTION
**Pull request by jsquire**
The focus of these changes is to add the Fabric Bot rules into the repository.

### CODE REVIEW

**Review by danieljurek — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
@jsquire
Would you let us know what the bot for? Any other repo having the bot and may I see their action?

**Comment by danieljurek** [comment]
This PR is stuck in validation for reasons unrelated to the current change -- https://dev.azure.com/azure-sdk/internal/_build/results?buildId=1378259&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=cb33ee24-f492-54d2-727a-ae0a7bb84b2c

How can we get this merged?

**Comment by weidongxu-microsoft** [comment]
@danieljurek 
No need to worry about CI. It is indeed not related, and fixed in latest main.

@srnagar Let me know if you are OK with it.
I see the same PR on azure-sdk-for-java is already merged https://github.com/Azure/azure-sdk-for-java/pull/27204

**Comment by danieljurek** [comment]
@weidongxu-microsoft -- Fabric bot documentation: https://eng.ms/docs/initiatives/open-source-at-microsoft/tools/fabricbot 

The rules that are in this PR are already being used on the repository by Fabric Bot and stored in a configuration in the Fabric Bot service. However, the Fabric Bot service is changing to require that the configuration be stored in the repository and this PR is to migrate storage of the Fabric Bot configuration from the Fabric Bot service to this repository.

**Comment by srnagar** [comment]
The build failure is due to a mismatch in javadocs of the generated files caused by [this PR](https://github.com/Azure/autorest.testserver/pull/343) which updated the swagger files to add more detailed doc comments.

**Pull request merged**
