### PR TITLE
verify new createSdkContext changes in tcgc

### PR DESCRIPTION
**Pull request by iscai-msft**

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
Change looks good.

Do we expect to use the 0.36.0-dev.2 here for release (user might get a conflict on their end when running tsp compile), or we can wait for 0.36.0

**Comment by iscai-msft** [comment]
@weidongxu-msft there won't be a conflict if you publish with the dev version, however this isn't a fix that needs to go out since it's all internal code.

**Comment by weidongxu-microsoft** [comment]
I am doing typespec version bump in this PR

**Pull request merged**
