### PR TITLE
[DO NOT MERGE] Showing code changes needed to make the demo work.

### PR DESCRIPTION
**Pull request by vcolin7**
I wrote [a sample app](https://github.com/vcolin7/openai-sample-app) that we can use to demonstrate how our generic-core allows it to communicate with the OpenAI service. There's plenty to do, like making the OpenAI client take models as parameters instead of BinaryData ([like a better version of this one](https://github.com/vcolin7/openai-sample-app/blob/main/src/main/java/org/example/ChatCompletionParameters.java)), but things work as is.

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
Thanks Victor.

I will fix the "bearer" one ASAP. (currently it follows the TSP scheme)

Let me see if the RestProxy overload is already there. If so, I will fix that one as well.

**Comment by weidongxu-microsoft** [comment]
For "making the OpenAI client take models as parameters instead of BinaryData". It should be there very soon.

I've have PR merged https://github.com/Azure/autorest.java/pull/2390. I just need to test it on the Azure OpenAI.

**Comment by weidongxu-microsoft** [comment]
`x-ms-error-code` seems not consistent. Some API has it and some not.

This relates to your service behavior. It is recommended to have it for all APIs.

**Comment by weidongxu-microsoft** [comment]
@vcolin7 

I've update the "openai" branch to latest, and regenerate the code.

It should include what you have here, as well as the model classes.

Plan to release a 0.11.0 with all these contained.

**Comment by vcolin7** [comment]
> Thanks Victor.
> 
> I will fix the "Bearer" one ASAP. (currently it follows the TSP scheme) I assume "Authentication" (as header name) is case insensitive? Does OpenAI having problem with this as well? https://stackoverflow.com/questions/5258977/are-http-headers-case-sensitive
> 
> Let me see if the RestProxy overload is already there. If so, I will fix that one as well.

You're right, the only thing we needed to update was Bearer started with an uppercase "B", the header name can be all lowercase and still work. @samvaity just added the `RestProxy` overload, so we should be good on that department as well.

**Pull request closed without merging**
