### PR TITLE
Check breaking change resilience using revapi

### PR DESCRIPTION
**Pull request by qwordy**
Resolve https://github.com/Azure/autorest.java/issues/1132

### CODE REVIEW

**Review by weidongxu-microsoft — COMMENTED** [review]
So all Java is generated?

Do you need to add to generate script?

**Comment by weidongxu-microsoft** [comment]
BTW, did you verify that it will report error if you manually changed the code to make the update package not backward compatible?

**Comment by qwordy** [comment]
> So all Java is generated?
> 
> Do you need to add to generate script?

It is generated. Added.

**Comment by qwordy** [comment]
> BTW, did you verify that it will report error if you manually changed the code to make the update package not backward compatible?

If I change
```diff
-    public Response<BinaryData> getRequiredWithResponse(RequestOptions requestOptions, Context context) {
+    public Response<BinaryData> getRequiredWithResponse(RequestOptions requestOptions, Context context, int x) {
         return this.serviceClient.getRequiredWithResponse(requestOptions, context);
     }
```
revapi will report
```
[ERROR] Failed to execute goal org.revapi:revapi-maven-plugin:0.14.3:check (default) on project llcupdate1: The following API problems caused the build to fail:
[ERROR] java.method.numberOfParametersChanged: method com.azure.core.http.rest.Response<com.azure.core.util.BinaryData> fixtures.llcresi.LLCClient::getRequiredWithResponse(com.azure.core.http.rest.RequestOptions, com.azure.core.util.Context, int):
The number of parameters of the method have changed.
```

**Review by weidongxu-microsoft — APPROVED** [review]

**Pull request merged**
