### PR TITLE
client, graalvm, error model alone need reflect, if stream-style-serialization

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
We don't need reflection for model/enum classes, if using azure-json.

But we still need reflection for error/exception classes, as azure-core initialize them.

Tested on compute, which have error model as `ApiError` and `InnerError`

### CODE REVIEW

**Comment by haolingdong-msft** [comment]
No test is impacted?

**Comment by weidongxu-microsoft** [comment]
> No test is impacted?

We only generate these (by default) for mgmt, and currently ths only mgmt tsp test has `stream-style-serialization=false`.

We should see them if there is new mgmt tsp test (i.e. Xiaofei's unmerged one in cadl-ranch).

**Comment by XiaofeiCao** [comment]
I added one when enabling stream-style for mgmt:
https://github.com/Azure/autorest.java/blob/main/typespec-tests/tsp/arm-stream-style-serialization.tsp

Seems no reflect config is generated. 
https://github.com/Azure/autorest.java/blob/main/typespec-tests/src/main/resources/META-INF/native-image/com.azure.resourcemanager/azure-resourcemanager-armstreamstyleserialization-generated/reflect-config.json

Though I don't have error types there.

**Comment by weidongxu-microsoft** [comment]
Yeah, for most common cases, generated SDK directly use ManagementError from azure-core-manangment, so it won't generate error model.

**Review by haolingdong-msft — APPROVED** [review]

**Pull request merged**
