### PR TITLE
tsp, try remove default on host

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
not able to handle here https://github.com/Azure/autorest.java/pull/2760

guess we could just remote it (anyway we don't need client default).

### CODE REVIEW

**Comment by haolingdong-msft** [comment]
I don't quite get why do we remove client default value?

**Comment by weidongxu-microsoft** [comment]
"next" version deprecated this "default". https://github.com/Azure/autorest.java/pull/2760

Also this wasn't suppose to be "client default".
```ts
    @doc("second-level domain, use httpbin")
    domain?: string = "httpbin",

    @doc("top-level domain, use org")
    tld?: string = "org",
```

It should be "server default".

**Review by haolingdong-msft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
I will put the compatibility of "next" for nightly to another PR.

**Pull request merged**
