### PR TITLE
tsp, fix for cases with invalid LRO response for new poll strategy

### PR DESCRIPTION
**Pull request by weidongxu-microsoft**
code upon https://github.com/Azure/autorest.java/pull/2394 and https://github.com/Azure/autorest.java/pull/2395
- code (mostly) https://github.com/Azure/autorest.java/commit/9fb264ed081756226427d13c3c6469f284f72c05
- test https://github.com/Azure/autorest.java/commit/213551d5c732c2e2185d69867f451724adb3c38f

code generated at https://github.com/Azure/azure-sdk-for-java/commits/add-samples_fix-lro (commit https://github.com/Azure/azure-sdk-for-java/commit/8b33b0294931e61f2a3310563ef1ef5bbd282592)

### CODE REVIEW

**Comment by weidongxu-microsoft** [comment]
> `!!` seems not a very good practice in TypeScript.

Any recommendation?

And if you have doc about `!!`, do let me know. Personally I saw a lot of this in typespec source code :-)

**Comment by weidongxu-microsoft** [comment]
copilot give me this

image

seems just what I'd want !! to do...

**Comment by haolingdong-msft** [comment]
Yes, it's a way to convert any value to boolean. But it's obsecure and can be lack of readibility. This is just a nit change. I will leave it to you to decide whether to update it.
image
image

https://stackoverflow.com/questions/784929/what-is-the-not-not-operator-in-javascript

**Review by haolingdong-msft — APPROVED** [review]

**Comment by weidongxu-microsoft** [comment]
Thanks. Update it and a few more.

**Pull request merged**
