### PR TITLE
Update pool used by `eng/pipelines/fluent_integration.yaml` to azsdk-pool-mms-win-2022-general / MMS2022Compliant

### PR DESCRIPTION
**Pull request by konrad-jamrozik**
Updating used pool to compliant image, v. 2022:
- https://github.com/Azure/azure-sdk-tools/issues/3407

### CODE REVIEW

**Review by weidongxu-microsoft — APPROVED** [review]
SDK repo seems be using "vmImage: MMS2022"
https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/platform-matrix.json#L8

Is there a difference?

**Comment by konrad-jamrozik** [comment]
> SDK repo seems be using "vmImage: MMS2022" https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/platform-matrix.json#L8
> 
> Is there a difference?

It should be also using `MMS2022Compliant`, thanks for pointing it out. I will make a PR updating it.

**Comment by konrad-jamrozik** [comment]
> > SDK repo seems be using "vmImage: MMS2022" https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/platform-matrix.json#L8
> > Is there a difference?
> 
> It should be also using `MMS2022Compliant`, thanks for pointing it out. I will make a PR updating it.

- https://github.com/Azure/azure-sdk-for-java/pull/33517

**Comment by konrad-jamrozik** [comment]
> > SDK repo seems be using "vmImage: MMS2022" https://github.com/Azure/azure-sdk-for-java/blob/main/eng/pipelines/templates/stages/platform-matrix.json#L8
> > Is there a difference?
> 
> It should be also using `MMS2022Compliant`, thanks for pointing it out. I will make a PR updating it.

- https://github.com/Azure/azure-sdk-for-java/pull/33517

**Pull request merged**
